import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css';
import CompatProvider from './compat-provider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        data-hide-dev-indicator={process.env.NODE_ENV === 'development' ? '1' : undefined}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CompatProvider>
          {children}
        </CompatProvider>
        <style
          dangerouslySetInnerHTML={{
            __html: `
              body[data-hide-dev-indicator="1"] nextjs-portal,
              body[data-hide-dev-indicator="1"] nextjs-portal [data-nextjs-toast],
              body[data-hide-dev-indicator="1"] [data-nextjs-toast],
              body[data-hide-dev-indicator="1"] [data-nextjs-error-overlay] {
                display: none !important;
              }
            `
          }}
        />
      </body>
    </html>
  );
}
